### ISSUE TITLE
Purpose of this project

### ISSUE THREAD

**Issue by jonathandick** [medigy/ux-react-lhc-form#1]
Hey, I'd love to learn more about the purpose of this project. Our team at OpenMRS is also interest in a react version of lhcforms. Please let me know more if possible. Thanks!

**Comment by shah** [comment]
Sure @jonathandick - we're building React wrappers for LHC Form and would love to collaborate. We've been trying to just "develop out in the open" so we're a little behind on documentation. If you want to drop me an email we can talk about our focus areas and see if they align with where you're going.

**Comment by jonathandick** [comment]
We are having a meeting tomorrow with LHC forms team to discuss potential co
